
services:
  db:
      image: mysql:8.0
      container_name: ocean_mysql
      restart: always
      ports:
        - "8306:3306"
      environment:
        MYSQL_DATABASE: ${DB_DATABASE:-ocean_db}
        MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-root}
      volumes:
        - mysql_data:/var/lib/mysql

  backend:
      build:
        context: .
        dockerfile: Dockerfile
      container_name: ocean_backend
      restart: always
      ports:
        - "8383:8383"
      env_file:
        - .env
      volumes:
        - ./backend:/var/www
<<<<<<< HEAD
      command: php artisan serve --host=0.0.0.0 --port=8383
=======
      command: sh -c "composer install && php artisan serve --host=0.0.0.0 --port=8383"
>>>>>>> 85eed9c2 (first commit)
      depends_on:
        - db
        
  frontend:
      image: node:20-alpine
      container_name: ocean_frontend
      restart: always
      ports:
        - "3302:3302"
      env_file:
        - .env
      volumes:
        - ./frontend:/app
      working_dir: /app
      command: sh -c "npm install && npm run dev -- --host 0.0.0.0 --port 3302"

volumes:
  mysql_data: