version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: php3-laravel
    restart: always
    ports:
      - "8306:3306"
    environment:
      MYSQL_DATABASE: ocean_db
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: