server {
    listen 8383;
    server_name _;

    # upload file product 50mb
    client_max_body_size 50M;

    root /var/www/public;
    index index.php index.html;

    # Charset
    charset utf-8;

    # Logging
    access_log /var/log/nginx/backend_access.log;
    error_log  /var/log/nginx/backend_error.log;

    # Laravel SPA routing
    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    # PHP-FPM fastcgi bridge
    location ~ \.php$ {
        fastcgi_pass backend:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        include fastcgi_params;
    }

    # Deny access to .htaccess
    location ~ /\.ht {
        deny all;
    }

    # Deny access to hidden files
    location ~ /\. {
        deny all;
    }
}
